name: CI Date

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:

  ubuntu:
    name: Job Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Run print date to ubuntu
        run: date
        
  windows:
    name: Job Windows
    runs-on: windows-latest
    steps:
      - name: Run print date to windows
        run: date
        
  macos:
    name: Job MacOs
    runs-on: macos-latest
    steps:
      - name: Run print date to mac os
        run: date
        
  jobfinal:
    name: Job final
    runs-on: ubuntu-latest
    needs: [ubuntu, windows, macos]
    steps:
      - name: Run success
        run: echo OK
